package com.example.shoptienhieu.constants;

public interface Permission {
    //quản lý người dùng
    String CREATE_USER = "CREATE_USER";
    String UPDATE_USER = "UPDATE_USER";
    String DETAIL_USER = "DETAIL_USER";
    String DELETE_USER = "DELETE_USER";
    String SEARCH_USER = "SEARCH_USER";
    String ACTIVE_USER = "ACTIVE_USER";
    //quản lý admin
    String CREATE_ADMIN = "CREATE_ADMIN";
    String UPDATE_ADMIN = "UPDATE_ADMIN";
    String DETAIL_ADMIN = "DETAIL_ADMIN";
    String DELETE_ADMIN = "DELETE_ADMIN";
    String SEARCH_ADMIN = "SEARCH_ADMIN";
    String ACTIVE_ADMIN = "ACTIVE_ADMIN";
    //quản lý phân quyền

    //quản lý thông tin shop
    String UPDATE_INFO_SHOP = "UPDATE_INFO_SHOP";
    //quản lý sản phẩm
    String SEARCH_PRODUCT = "SEARCH_PRODUCT";
    String CREATE_PRODUCT = "CREATE_PRODUCT";
    String UPDATE_PRODUCT = "UPDATE_PRODUCT";
    String DETAIL_PRODUCT = "DETAIL_PRODUCT";
    String DELETE_PRODUCT = "DELETE_PRODUCT";
    String CHANGE_STATUS_PRODUCT = "CHANGE_STATUS_PRODUCT";
    // quản lý chiến dịch
    String SEARCH_CAMPAIGN = "SEARCH_CAMPAIGN";
    String CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
    String UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
    String DETAIL_CAMPAIGN = "DETAIL_CAMPAIGN";
    String DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
    String CHANGE_STATUS_CAMPAIGN = "CHANGE_STATUS_CAMPAIGN";
    //quản lý đơn hàng
    String SEARCH_INVOICE = "SEARCH_INVOICE";
    String CREATE_INVOICE = "CREATE_INVOICE";
    String UPDATE_INVOICE = "UPDATE_INVOICE";
    String DETAIL_INVOICE = "DETAIL_INVOICE";
    String DELETE_INVOICE = "DELETE_INVOICE";
    String CHANGE_STATUS_INVOICE = "CHANGE_STATUS_INVOICE";
    //quản lý hình thức vận chuển
    String SEARCH_DELIVERY = "SEARCH_DELIVERY";
    String CREATE_DELIVERY = "CREATE_DELIVERY";
    String UPDATE_DELIVERY = "UPDATE_DELIVERY";
    String DETAIL_DELIVERY = "DETAIL_DELIVERY";
    String DELETE_DELIVERY = "DELETE_DELIVERY";
    String CHANGE_STATUS_DELIVERY = "CHANGE_STATUS_DELIVERY";
    //quản lý phương thức thanh toán
    String SEARCH_PAYMENT = "SEARCH_PAYMENT";
    String CREATE_PAYMENT = "CREATE_PAYMENT";
    String UPDATE_PAYMENT = "UPDATE_PAYMENT";
    String DETAIL_PAYMENT = "DETAIL_PAYMENT";
    String DELETE_PAYMENT = "DELETE_PAYMENT";
    String CHANGE_STATUS_PAYMENT = "CHANGE_STATUS_PAYMENT";
    //quản lý xuất xứ
    String SEARCH_ORIGIN = "SEARCH_ORIGIN";
    String CREATE_ORIGIN = "CREATE_ORIGIN";
    String UPDATE_ORIGIN = "UPDATE_ORIGIN";
    String DETAIL_ORIGIN = "DETAIL_ORIGIN";
    String DELETE_ORIGIN = "DELETE_ORIGIN";
    String CHANGE_STATUS_ORIGIN = "CHANGE_STATUS_ORIGIN";
    //quản lý danh mục
    String SEARCH_CATEGORY = "SEARCH_CATEGORY";
    String CREATE_CATEGORY = "CREATE_CATEGORY";
    String UPDATE_CATEGORY = "UPDATE_CATEGORY";
    String DETAIL_CATEGORY = "DETAIL_CATEGORY";
    String DELETE_CATEGORY = "DELETE_CATEGORY";
    String CHANGE_STATUS_CATEGORY = "CHANGE_STATUS_CATEGORY";
    //quản lý thương hiệu
    String SEARCH_BRAND = "SEARCH_BRAND";
    String CREATE_BRAND = "CREATE_BRAND";
    String UPDATE_BRAND = "UPDATE_BRAND";
    String DETAIL_BRAND = "DETAIL_BRAND";
    String DELETE_BRAND = "DELETE_BRAND";
    String CHANGE_STATUS_BRAND = "CHANGE_STATUS_BRAND";
    //thống kê
    String STATISTIC_ADMIN = "STATISTIC_ADMIN";
    String STATISTIC_SHOP = "STATISTIC_SHOP";
    //quản lý tìm kiếm




}
